/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/lowTree_01.glb");
  return (
    <group ref={group} {...props} dispose={null} castShadow>
      <mesh
        castShadow
        geometry={nodes.Cube.geometry}
        material={materials.brown}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere.geometry}
        material={materials.green_2}
        position={[-0.14, 8.92, -1.6]}
        rotation={[-0.43, -0.15, -0.12]}
        scale={[1.17, 0.7, 1.1]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere001.geometry}
        material={materials.green_2}
        position={[1.69, 8.07, 0.49]}
        rotation={[-0.12, 0.06, -0.23]}
        scale={[1.69, 1, 1]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere002.geometry}
        material={materials.green_2}
        position={[-2.03, 7.55, 0.46]}
        rotation={[0.52, 0.59, 0.11]}
        scale={[1.69, 1, 1]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere003.geometry}
        material={materials.green_3}
        position={[3.55, 6.74, 0.84]}
        rotation={[-0.6, 1.06, 0.74]}
        scale={[1.3, 0.77, 0.77]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere004.geometry}
        material={materials.green_2}
        position={[-4.5, 5.64, 1.8]}
        rotation={[1.68, 0.48, -0.81]}
        scale={[1.3, 0.77, 0.77]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere005.geometry}
        material={materials.green_2}
        position={[2.47, 6.18, 4.21]}
        rotation={[-0.39, 0.23, 0.07]}
        scale={[1.69, 1, 1]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere006.geometry}
        material={materials.green_3}
        position={[1.08, 7.56, -4.11]}
        rotation={[-0.22, -0.09, -0.18]}
        scale={[1.69, 1, 1]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere007.geometry}
        material={materials.green_1}
        position={[0.78, 5.69, -3.8]}
        rotation={[-0.13, -0.64, 0.39]}
        scale={[1.17, 0.7, 1.1]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere008.geometry}
        material={materials.green_1}
        position={[-4.41, 4.38, -0.52]}
        rotation={[-0.95, -0.56, 0.65]}
        scale={[2.18, 1.29, 1.29]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere009.geometry}
        material={materials.green_3}
        position={[-0.4, 7.57, 0.4]}
        rotation={[1.88, 0.94, -1.62]}
        scale={[1.3, 0.77, 0.77]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere010.geometry}
        material={materials.green_1}
        position={[2.18, 4.32, 4.54]}
        rotation={[-3.13, -0.23, 0.12]}
        scale={[0.87, 0.51, 0.51]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere011.geometry}
        material={materials.green_2}
        position={[3.32, 3.64, 3.4]}
        rotation={[-0.45, 0.69, -1.52]}
        scale={[1.69, 1, 1]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere012.geometry}
        material={materials.green_1}
        position={[2.28, 6.87, 0.84]}
        rotation={[2.97, -0.55, -0.04]}
        scale={[0.51, 0.3, 0.3]}
      />
      <mesh
        castShadow
        geometry={nodes.Icosphere013.geometry}
        material={materials.green_1}
        position={[0.58, 7.35, -0.11]}
        rotation={[2.97, -0.55, -0.04]}
        scale={[0.51, 0.3, 0.3]}
      />
    </group>
  );
}

useGLTF.preload("/lowTree_01.glb");
